### ISSUE TITLE
Tratamento de Exceções na View

### ISSUE THREAD

**Issue by wbs2A** [wbs2A/BancoLPOO#1]
Os métodos do Controller lançarão exceções à view e os retornos serão objetivos.
Solicita-se que as exceções sejam tratadas e os retornos sejam os mais diretos possíveis.
Aqui serão levantadas possíveis exceções que os métodos de CRUD e outras operações possam lançar.

**Comment by DOUGLASMD1** [comment]
O método getSessao() deve lançar uma exceção de Usuário inexistente, caso não haja ninguém na sessão e retornar a Pessoa contida na sessão.
