### ISSUE TITLE
Alterações para esta semana e para semana que vem

### ISSUE THREAD

**Issue by nathalyamaral** [wbs2A/BancoLPOO#11]
Comunico a todos as solicitações de alteração na aplicação para esta semana e para a semana que vem. 

Para esta semana: 
	

- Conta (backspace - espaço) como um caractere na senha
-  Permitir Acentuação no cadastro nome
-  Codificação utf-8 para não tiver erros de formação nos prints
-  Data de nascimento arrumar formato em português
-  Colisão de número de conta se já existir
-  Se tem uma conta só ela é Padrão 
-  Verificar deposito conta não existente
-  Comentários javadoc em todos os métodos, descrição de classes e descrição de pacotes
-  Alterar nome métodos (realiza transação) e transformar em apenas um (Método que adiciona transação no extrato <Movimentações>)
-  Arrumar extrato (Data, hora, tipo, valor e no final o valor atual, se for transferência apresentar quem realizou a transferência)
-  Alteração da forma de apresentar menu gerenciamento de conta, exemplo (Se o usuário tiver 1 conta padrão apresentar um tipo de menu.| Se o usuário tiver mais de duas contas apresentar o mesmo menu que permite escolher se a operação é na conta padrão ou outra conta) 

Para semana que vem:
-  Opção ajuda irá abrir um manual
-  Máscara de senha
-  Criptografar senha
-  Botão desistir 
-  Botão voltar
-  Recuperar informações de login
-  Servidor de email 
-  Remover uso do enter
-  Usar teclas de funções (ESC, F1, F2, F3.....) 
-  Interface

Observação: Agora que todos podem dar commit em qualquer pacote, para gerênciamento disso definimos um líder de cada pacote, que entenda 100% do funcionamento deste pacote, isto afim de evitar que realizem uma alteração que não venha afetar outras funcionalidades, também para consultar se a alteração já foi feita ou é realmente necessária. Anexo lista dos líderes e informações de contato.

	- Pacote View: Michael Douglas (micheldouglas97@hotmail.com) @DOUGLASMD1 
	- Pacote Model: Valdenize. (valdenizesilva8@gmail.com) @ValdenizeRibeiro 
	- Pacote Controller, Exception, Banco(Main): Náthaly (nathalyamaral07@gmail.com)

**Comment by allison-araujo** [comment]
Funcionalidades já arrumadas.

Permitir Acentuação no cadastro nome
Codificação utf-8 para não tiver erros de formação nos prints
Data de nascimento arrumar formato em português
Colisão de número de conta se já existir

**Comment by nathalyamaral** [comment]
Todas as alterações dessa semana foram realizadas.
