### ISSUE TITLE
Solicitações de alteração em Model

### ISSUE THREAD

**Issue by nathalyamaral** [wbs2A/BancoLPOO#8]
@ValdenizeRibeiro @AllisonVinicius @HelmuthOssinaga 

Favor atender as seguintes solicitações de alteração descritas a seguir:

1 - Corrigir a falta de atributos na classe Movimentações:
Atributos (date, Conta destino, Conta conta, nome da operação, valor, numero da operação e o saldo anterior).

2 - Corrigir Construtor classe Movimentações:
- Movimentacoes(date, conta, nomedaoperacao, valor, num_operacao); para saque e deposito
- Movimentacoes(date, contadestino, contaremetente, nomedaoperacao, valor, num_operacao); para transferência

3 - Adicionar toString (que imprime o extrato da conta):
O toString deverá conter
		- Data em formato de date não em string.
		- Nome do cliente
		- Agencia
		- Numero da conta
		- Saldo anterior (se refere ao saldo anterior a operação)
		- Descrição 
		- Valor
		- Numero da operação relacionado ao nome (apresentar nome de acordo com o numero da operação)
		- Saldo atual (se refere ao saldo após a operação)

**Comment by ValdenizeRibeiro** [comment]
@nathalyamaral  as alterações devem ser feitas ainda no Development ou no master?
E o atributo boolean aconteceu deve ser retirado da class?

**Comment by nathalyamaral** [comment]
No Development, o atributo boolean pode deixar é importante para armazenar essa movimentação no extrato só se aconteceu, agradeço desde já as alterações.

**Comment by ValdenizeRibeiro** [comment]
o que seria descrição?

**Comment by DOUGLASMD1** [comment]
@ValdenizeRibeiro Seria um detalhamento se o usuário quisesse descrever algo mais. Como tem uma forma de saber o que realmente ele fez no pagamento é uma forma disponibilizar detalhes no extrato.

**Comment by DOUGLASMD1** [comment]
*Nao tem...

**Comment by DOUGLASMD1** [comment]
Deixa string mesmo. Ai deixa aberto isso pra ele!

**Comment by DOUGLASMD1** [comment]
@ValdenizeRibeiro  Não esquece que no caso de transferência você precisa montar uma outra forma de armazenar pra quem foi essa transferência.

**Comment by ValdenizeRibeiro** [comment]
vou adicionar um atributo string Descricao, logo @DOUGLASMD1 adiciona na views esta possível entrada e @nathalyamaral por favor passe para o construtor.

**Comment by allison-araujo** [comment]
??

2018-06-03 12:29 GMT-05:00 náthaly. <notifications@github.com>:

**Comment by nathalyamaral** [comment]
fechado, pois as alterações solicitadas foram todas realizadas com sucesso.
